### PR TITLE
Rossback pages upload

### PR DESCRIPTION
**Pull request by Rossback**
This just adds the build directory in hopes that pages will work now

### CODE REVIEW

**Comment by IKEAKart** [comment]
What needs to be added for it to not cause an error??

**Comment by Rossback** [comment]
> What needs to be added for it to not cause an error??

I am unsure. Normally when a test fails it will say *why* or *where* it failed, but with this one it just says "This job failed."
image

**Comment by Rossback** [comment]
Here are some examples of what it **should** look like:
image
image

**Comment by Rossback** [comment]
For some reason the errors are showing themselves now, and the error seems to be due to branch protections from the pull request, I have reason (albeit a very small reason) to believe it MAY fix itself if we merge this into main.
image

**Review by MDorn03 — APPROVED** [review]
Approving despite issues per request

**Pull request merged**
